version: '3.8'
services:
  hazelcast1:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast1
    volumes:
      - "${CD}/hazelcast.yml:/opt/hazelcast/hazelcast.yml"
    ports:
      - "5701:5701"
    networks:
      - hazelcast-network

  hazelcast2:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast2
    volumes:
      - "${CD}/hazelcast.yml:/opt/hazelcast/hazelcast.yml"
    ports:
      - "5702:5701"
    networks:
      - hazelcast-network

  hazelcast3:
    image: hazelcast/hazelcast:latest
    container_name: hazelcast3
    volumes:
      - "${CD}/hazelcast.yml:/opt/hazelcast/hazelcast.yml"
    ports:
      - "5703:5701"
    networks:
      - hazelcast-network

  management-center:
    image: hazelcast/management-center:latest
    container_name: management-center
    ports:
      - "8090:8080"
    networks:
      - hazelcast-network

networks:
  hazelcast-network:
    driver: bridge
